### ISSUE TITLE
Spawn the auto-generated iCub raw models in the composite Gazebo models (iCub fixed, iCub on seesaw, ...)

### ISSUE THREAD

**Issue by diegoferigo** [robotology-playground/icub-gazebo-wholebody#16]
The `feature/useGeneratedModels` branch will get merged into `master` after all the tests on the new autogenerated models will be performed.

There are notable changes in the usage of this repository, particularly it is not possible anymore to point the env variables directly on the cloned repo, but at least a CMake configuration step is now required.

The reason is that now there are templated `.in` files to select the active robot model (which can be only one at a time), that must be specified with the `-DDROBOT_NAME` CMake option. Further infos on the branch's README.

[Currently only `icub-fixex-nohands` has this support](https://github.com/robotology-playground/icub-gazebo-wholebody/pull/12), and it should be extended to all the other models in this repository.
For extending the use of the iCub generated model in composite models like "iCub on seesaw", we need to override the model default joint configuration.

So the changes implemented by this Epic are listed below:
- Create the model.config.in for all the models which would require it
- Override model default joint configuration in the root gazebo model or world sdf

**Comment by traversaro** [comment]
We encountered this issue with @VenusPasandi : in particular, at the moment if someone wants to use the `iCubGazeboV2_5` fixed base model, this is not possible unless you manually modify the `icub_fixed_no_hands` model. 

This is a pity, as we should actually suggest most of the users involved in control-related research activities to use the `iCubGazeboV2_5` models as much as possible, as for the `icubGazeboSim` model we do not have any guarantee of the consistency of the inertial parameters between the SDF model simulated in Gazebo and the URDF model used in the control software (this could be also nicely solved by supporting loading SDF in iDynTree https://github.com/robotology/idyntree/issues/481, but this is another story). 

@DanielePucci any chance of getting someone to work on this?

**Comment by DanielePucci** [comment]
@traversaro 
It seems to me that this is somewhat important since, though not blocking, it slows down the simulation process. As soon as @nunoguedelha finishes writing his thesis, this could be a task after thesis submission

**Comment by nunoguedelha** [comment]
ok for me, as soon as the thesis is submitted then.

@traversaro , I don't understand what you mean in your last comment..
> We encountered this issue with @VenusPasandi : in particular, at the moment if someone wants to use the `iCubGazeboV2_5` fixed base model, this is not possible unless you manually modify the `icub_fixed_no_hands` model.

today three models can already be used with the URDF generated from CAD: "iCubGenovaV2_5 fixed" (base fixed on a pole), "iCubGenovaV2_5 feet fixed", "iCubGenovaV2_5 standing". What was missing was https://github.com/robotology/icub-gazebo-wholebody/issues/18 for overriding the root URDF model joint configuration with the one in the composite model, and https://github.com/robotology/gazebo-yarp-plugins/issues/392 implements one of the required bricks, right?

**Comment by nunoguedelha** [comment]
> What was missing was [](https://github.com/robotology/icub-gazebo-wholebody/issues/18)

... for spawning the remaining models I mean (iCub sitting on a chair, etc...).

**Comment by traversaro** [comment]
> today three models can already be used with the URDF generated from CAD: "iCubGenovaV2_5 fixed" (base fixed on a pole), "iCubGenovaV2_5 feet fixed", "iCubGenovaV2_5 standing". 

This is done using the `feature/useGeneratedModels`, right?

**Comment by traversaro** [comment]
> What was missing was #18 for overriding the root URDF model joint configuration with the one in the composite model, and robotology/gazebo-yarp-plugins#392 implements one of the required bricks, right?

Yes, @lrapetti is working on it.

**Comment by nunoguedelha** [comment]
> This is done using the `feature/useGeneratedModels`, right?

yes. If I remember well, it was not merged yet in the master because of the missing joint reconfiguration and https://github.com/robotology/icub-gazebo-wholebody/issues/18.

**Comment by gabrielenava** [comment]
Closing. Refer also to https://github.com/robotology/icub-gazebo-wholebody/issues/18
