### ISSUE TITLE
Override model default joint configuration in the root gazebo model or world sdf

### ISSUE THREAD

**Issue by nunoguedelha** [robotology-playground/icub-gazebo-wholebody#18]

**Comment by lrapetti** [comment]
This task is addressed in https://github.com/robotology/gazebo-yarp-plugins/issues/392

**Comment by lrapetti** [comment]
@nunoguedelha With https://github.com/robotology/gazebo-yarp-plugins/pull/401, this can now be achieved using the `configurationOverride` plugin.

You can find the model implementing this feature in the `devel` branch of `icub-gazebo-wholebody`. I think this issue may be closed.

**Comment by traversaro** [comment]
I agree that both this issue and https://github.com/robotology/icub-gazebo-wholebody/issues/16 can now be closed. @gabrielenava

**Comment by gabrielenava** [comment]
Closing the issue.
