### ISSUE TITLE
Move to robotology

### ISSUE THREAD

**Issue by traversaro** [robotology-playground/icub-gazebo-wholebody#20]
@gabrielenava ?

**Comment by gabrielenava** [comment]
I am ok with moving the ropo to robotology, I can handle this.

**Comment by traversaro** [comment]
You need admin power in robotology. If you are ok with this, I can proceed.

**Comment by gabrielenava** [comment]
Ok! for me is fine. I think we need to update also the `robotology-superbuild`

**Comment by traversaro** [comment]
Yep. Fortunately GitHub redirect features are great, so we can handle this after the move.

**Comment by traversaro** [comment]
Done (see https://github.com/robotology/icub-gazebo-wholebody). 
Opening a separate issue in the superbuild.

**Comment by yeshasvitirupachuri** [comment]
@traversaro any particular reason to move to robotology? 
Currently, we have [human-gazebo](https://github.com/robotology-playground/human-gazebo) in robotology-playground. Although it is not very actively used at the moment, it will contain all the files related the human urdf/sdf files that will be used in AnDy project, which hopefully will be available for other partners to use at a later stage. So, should we also consider moving this repo to `robotology` ??

**Comment by traversaro** [comment]
`robotology-playground` is only meant as a temporary location for experimental repository. If a repository is widely used, I suggest to avoid using `robotology-playground`, if only for its name that does not really communicated seriousness.
