### ISSUE TITLE
Create devel branch

### ISSUE THREAD

**Issue by lrapetti** [robotology-playground/icub-gazebo-wholebody#21]
@gabrielenava 
I think we may create a `devel` branch updated with https://github.com/robotology/gazebo-yarp-plugins/tree/devel. It would be useful for example to test the usage of a single `icub` model with different initial configurations (e.g. in [`icub_on_seesaw`](https://github.com/robotology/icub-gazebo-wholebody/tree/master/models/icub_on_seesaw) or [`icub_standup`](https://github.com/robotology/icub-gazebo-wholebody/tree/master/models/icub_standup)) as described in https://github.com/robotology/gazebo-yarp-plugins/issues/392.

**Comment by gabrielenava** [comment]
I agree on this. I will review the documentation of this [PR](https://github.com/robotology/gazebo-yarp-plugins/pull/401) and I will try to apply this plugin to the `seesaw` and `icub-on-chair` models. If I manage to do it, then I will push the modified models in this repo in a new branch called `devel`.

**Comment by gabrielenava** [comment]
devel branch has been created: https://github.com/robotology/icub-gazebo-wholebody/tree/devel

Closing this issue.

**Comment by traversaro** [comment]
Can you update https://github.com/robotology/robotology-superbuild/blob/master/cmake/ProjectsTagsDevel.cmake ? Thanks!

**Comment by lrapetti** [comment]
@gabrielenava 
following https://github.com/robotology/QA/issues/358, I think we can think of merging the `devel` into `master`.
