### ISSUE TITLE
Release version for robotology-superbuild 2020.02

### ISSUE THREAD

**Issue by traversaro** [robotology-playground/icub-gazebo-wholebody#29]
Hi @gabrielenava, regarding https://github.com/robotology/robotology-superbuild/issues/331, it would be possible to release a version of this repo (the version number does not matter, `v0.1.0` would be ok)? Thanks!

**Comment by gabrielenava** [comment]
I created this: https://github.com/robotology/icub-gazebo-wholebody/releases/tag/v0.1.0

Is it ok in this way @traversaro ?

**Comment by traversaro** [comment]
> 
> 
> I created this: https://github.com/robotology/icub-gazebo-wholebody/releases/tag/v0.1.0
> 
> Is it ok in this way @traversaro ?

Perfect. Minor comment: probably I would avoid to reference 2020.02 in the release title, as if there are not modifications, it is possible that v0.1.0 will be the release that we use for 2020.02, 2020.05, 2020.08, etc etc.

**Comment by traversaro** [comment]
In any case, I think we can close the issue.

**Comment by gabrielenava** [comment]
Changed a bit the title and closing the issue, thanks.
