### ISSUE TITLE
Problem in including URDF in  SDF 1.4 model

### ISSUE THREAD

**Issue by traversaro** [robotology-playground/icub-gazebo-wholebody#30]
Apparently there is a bug  in SDFormat >= 8.4 (basically after this PR https://bitbucket.org/osrf/sdformat/pull-requests/575/parse-urdf-files-to-sdf-15-instead-of-14/diff). In a nutshell, what apparently is happening is that the model is silently parsed with the wrong joint axis.

This problem could  affect some models contained in this repo: 
* https://github.com/robotology/icub-gazebo-wholebody/blob/master/models/icub_fixed_no_hands/icub_fixed_no_hands.sdf#L2
* https://github.com/robotology/icub-gazebo-wholebody/blob/master/models/icub_feet_fixed/icub_feet_fixed.sdf#L2

Updating the models to SDF  version 1.5 should fix the problem with SDFormat >= 8.4 while remaining compatible with older  SDFormat versions.

**Comment by traversaro** [comment]
Thanks to @ale-git for reporting the problem.

**Comment by traversaro** [comment]
Interestingly the models added by @S-Dafarra  in https://github.com/robotology/icub-models/pull/27 already used SDF 1.5, so they are not affected by this bug.

**Comment by traversaro** [comment]
The problem was reported by @ale-git  on a system that was using sdformat 9.1, but I was unable to reproduce it on sdformat 9.2 , so unless somebody is able to reproduce it on a system with the latest sdformat I think it does not make sense to debug it. 

@azeey @EricCousineau-TRI this was the issue that we discussed in https://osrf-migration.github.io/sdformat-gh-pages/#!/osrf/sdformat/pull-requests/575/page/1 , but unfortunately I am not able to reproduce it even using the original model that showed the problem. Sorry for the noise.

**Comment by EricCousineau-TRI** [comment]
No worries! It might have been that Steve and Addisu had fixed the issue in 9.2 itself.

Some potential candidates:
* https://github.com/osrf/sdformat/blame/96cc8d2/Changelog.md#L62
* https://github.com/osrf/sdformat/blame/96cc8d2/Changelog.md#L43
* https://github.com/osrf/sdformat/blame/96cc8d2/Changelog.md#L34

**Comment by traversaro** [comment]
Perfect, thanks @EricCousineau-TRI !
