### ISSUE TITLE
Move to robotology-legacy and archive?

### ISSUE THREAD

**Issue by traversaro** [robotology-playground/icub-gazebo-wholebody#31]
Given the discussion in https://github.com/robotology/robotology-superbuild/issues/543, should we move this in robotology-legacy and archive? @gabrielenava

**Comment by gabrielenava** [comment]
I agree with the moving, if there will be some models from this repo that we will need in the future we will move them in icub-models repo.

**Comment by traversaro** [comment]
I moved the repo in https://github.com/robotology-legacy/icub-gazebo-wholebody, let's archive it.
